### ISSUE TITLE
How to set multiple attributes in data binding?

### ISSUE THREAD

**Issue by dseeker** [a-ignatov-parc/tvdml#57] opened 2021-06-21 10:35 UTC
In the documentation it states we can add `@src` attribute binding to the DataItems object
```js
<img binding="@src:{url};" width="300" height="300" />
```
How to do the same with another attribute, like class together with src on the same element?

**Comment by a-ignatov-parc** [comment] 2021-06-21 11:49
Not 100% sure, but I think this should work

```xml
<img binding="@src:{url};@class:{class};" width="300" height="300" />
```

**Comment by dseeker** [comment] 2021-06-21 21:10
I see the elements with the correct attributes in the inspector but it does not render the UI, probably some limitation on the TVML engine which might not support it, I haven't seen any example from Apple about multiple attributes

**Comment by a-ignatov-parc** [comment] 2021-06-22 06:23
If you see attributes configured via data binding in devtools, these are definitely some issues with TVML rendering engine. The best thing to do here is to report the bug to Apple 👍 

Since it seems that the problem is not with the library, I'll close this issue

**Closed as completed by a-ignatov-parc** 2021-06-22 06:23 UTC
