### ISSUE TITLE
tvOS 12 and Xcode 10 errors and crashes

### ISSUE THREAD

**Issue by febbraro** [a-ignatov-parc/tvdml#39] opened 2018-10-05 17:58 UTC
Have you experienced any issues running a TVMLKit (and specifically TVDML) on tvOS 12 and xcode 10?  Since upgrading I'm getting quite a few `Styles` errors as well as application crashes these happen in both the simulator and on an actual device.

The style errors look like (there are 100s of these errors)

`[Styles] Registering a style (color) that already has an existing type (0) that doesn't match the new type (4)`
and
`[Styles] Unexpected declartion type for style "text-shadow"`

and the app crashes after navigating around a few page with the following errors

```
AppName(5399,0x700001de8000) malloc: *** error for object 0x600003bc79c0: pointer being freed was not allocated
AppName(5399,0x700001de8000) malloc: *** set a breakpoint in malloc_error_break to debug
(lldb) 
```
```
libsystem_kernel.dylib`__pthread_kill:
    0x10a5a8b7c <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148 
    0x10a5a8b81 <+5>:  movq   %rcx, %r10
    0x10a5a8b84 <+8>:  syscall 
->  0x10a5a8b86 <+10>: jae    0x10a5a8b90               ; <+20>
    0x10a5a8b88 <+12>: movq   %rax, %rdi
    0x10a5a8b8b <+15>: jmp    0x10a5a2e67               ; cerror_nocancel
    0x10a5a8b90 <+20>: retq   
```

I don't see any mention of these kind of errors with tvOS/TVMLKit anywhere else so I was wondering if others using TVDML were experiencing the same thing.

**Comment by spunkedy** [comment] 2018-10-05 20:10
I did notice a lot of those actually

On Oct 5, 2018 12:58 PM, "Frank Febbraro" <notifications@github.com> wrote:

Have you experienced any issues running a TVMLKit (and specifically TVDML)
on tvOS 12 and xcode 10? Since upgrading I'm getting quite a few Styles
errors as well as application crashes these happen in both the simulator
and on an actual device.

The style errors look like (there are 100s of these errors)

[Styles] Registering a style (color) that already has an existing type (0)
that doesn't match the new type (4)
and
[Styles] Unexpected declartion type for style "text-shadow"

and the app crashes after navigating around a few page with the following
errors

AppName(5399,0x700001de8000) malloc: *** error for object
0x600003bc79c0: pointer being freed was not allocated
AppName(5399,0x700001de8000) malloc: *** set a breakpoint in
malloc_error_break to debug
(lldb)

libsystem_kernel.dylib`__pthread_kill:
    0x10a5a8b7c <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148
    0x10a5a8b81 <+5>:  movq   %rcx, %r10
    0x10a5a8b84 <+8>:  syscall
->  0x10a5a8b86 <+10>: jae    0x10a5a8b90               ; <+20>
    0x10a5a8b88 <+12>: movq   %rax, %rdi
    0x10a5a8b8b <+15>: jmp    0x10a5a2e67               ; cerror_nocancel
    0x10a5a8b90 <+20>: retq

I don't see any mention of these kind of errors with tvOS/TVMLKit anywhere
else so I was wondering if others using TVDML were experiencing the same
thing.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/a-ignatov-parc/tvdml/issues/39>, or mute the thread

**Comment by a-ignatov-parc** [comment] 2018-10-06 05:28
This is definitely something new 🤔 I'll investigate it.

@febbraro are you using `color` and `text-shadow` styles in your application?

**Comment by a-ignatov-parc** [comment] 2018-10-06 05:46
Well, empty TVML app still generates a lot of style warning even when there is nothing to show. I guess Apple broke something either in XCode or tvOS 12 🤷‍♂️ 

I'll post a bug report for this issue.

**Comment by a-ignatov-parc** [comment] 2018-10-06 05:47
@spunkedy you were talking about style warnings or app crashes?

**Comment by a-ignatov-parc** [comment] 2018-10-06 06:14
@febbraro I've tested three apps with different navigation structure and complexity and there were no crashes. Can you share a hint or a minimum app with a repro case?

**Comment by spunkedy** [comment] 2018-10-07 07:48
@a-ignatov-parc style warnings. I haven't seen any crashes that weren't directly caused by me doing something silly like accessing a property that didn't exist on an object.

**Comment by spunkedy** [comment] 2018-10-07 07:50
![styles](https://user-images.githubusercontent.com/690735/46579657-af3f9280-c9db-11e8-9eb8-69ed81e8803e.gif)

**Comment by a-ignatov-parc** [comment] 2018-10-08 08:16
I've submitted a bug report for these styles warnings in the tvOS 12. When Apple responds I'll post an update.

**Comment by febbraro** [comment] 2018-10-08 16:43
I'll see what I can pull together that can recreate the crash

**Comment by febbraro** [comment] 2018-10-09 01:01
Ok I have a sample project here, https://github.com/febbraro/xcode10-tvos12

To test, go into the `web/` directory and run `npm install` and `npm run serve` to get the test server running (http://localhost:9001/application.js)

Then run the xcode project in the simulator.  To get the crash, select the single video tile to get to the detail page, then hit menu(esc) to go back and enter for the details page again and esc to go back....do this about 4 or 5 times and it will crash.

**Comment by a-ignatov-parc** [comment] 2018-10-09 06:59
@febbraro nice! Thanks! Will check it soon 👍

**Comment by a-ignatov-parc** [comment] 2018-10-09 08:14
Well, there is some reference leak happening that crash app. I'll continue my investigation and will post updates here.

**Comment by a-ignatov-parc** [comment] 2018-10-09 09:50
@febbraro created a fix for this problem. I need more time to test it and if everything will be ok I'll release it.

**Comment by febbraro** [comment] 2018-10-09 16:03
That’s great! Thanks. Would you mind sharing how you figured out what the problems were? I was unsure how to start debugging this problem. I would have loved to do more exploration to help get to the problem.

**Comment by a-ignatov-parc** [comment] 2018-10-09 16:11
Sure! I started from deleting everything until it starts to work and then added small parts to localize the problem part of the code.

Unfortunately, XCode doesn't help with debugging TVML apps 😞

**Comment by febbraro** [comment] 2018-10-09 19:45
So in your fix you are adding unique IDs to each node and using those to find their references later on for comparison. Is that making a stronger reference to the object? or is it really just calling `console.info` with a reference to the node that is holding a tighter reference on the object?

(or do I have the idea behind the fix completely wrong?)

**Comment by a-ignatov-parc** [comment] 2018-10-09 20:42
We use IDs instead of storing references to nodes and `console.info` give us time to clean react runtime before OS will GC everything on the document's disposal. We could store nodes in `Map` but that would require us to clean everything manually on unmount or we'll get a memory leak. `console.info` is a cheap workaround that handles cleanup by the OS itself.

**Comment by a-ignatov-parc** [comment] 2018-10-14 16:41
@febbraro sorry for a long silence was very busy. Checked all cases that I was concerned of and everything seems to look good. 

Released fix under [`v6.2.0`](https://github.com/a-ignatov-parc/tvdml/releases/tag/v6.2.0). Please take a look and if the issue persists don't hesitate to reopen this issue 😉

**Comment by febbraro** [comment] 2018-10-15 19:33
@a-ignatov-parc Thanks so much for getting the fix out.  The bad news is that I still get the error, it just does not occur so quickly.  I have had the same crash after a fe wminute break and then start using the app again. I have seen it spontaneously after some heavy app usage it randomly crashed while the app was idle.

My real app has quite a few more video tiles, I will see if I can replicate a good amount of data in the test app and get the same crash.

**Comment by febbraro** [comment] 2018-10-15 22:02
Ok, I added a lot more data here: https://github.com/febbraro/xcode10-tvos12

And following the same steps (and doing a bunch of scrolling on the main screen) I can get the crashes to happen every time.

**Comment by a-ignatov-parc** [comment] 2018-10-18 17:53
@febbraro I think I have managed to fix this problem in [`v6.2.1`](https://github.com/a-ignatov-parc/tvdml/releases/tag/v6.2.1). Please check it and let me know.

**Comment by febbraro** [comment] 2018-10-18 18:19
@a-ignatov-parc Thanks for the update. I will test it out today and get back to you.

**Comment by febbraro** [comment] 2018-10-19 00:01
So, after some testing, the sample project I provided does execute without error.  My actual project, however, still contains errors. They are a bit different now.

The style warnings are still there in the real project and simulator.

This "error" is logged each time a new page is pushed onto the navigationDocument.

`<Error>: Unable to create elements for document <undefined itmlID="id_2"/>`
The itmlID is always 2, but I get this with the test project too and there are no crashes with that

The error I get now is `ITMLKit (10): EXC_BAD_ACCESS (code=1, address=0x51)`

```
libxml2.2.dylib`xmlSetTreeDoc:
    0x10588a06a <+0>:   pushq  %rbp
    0x10588a06b <+1>:   movq   %rsp, %rbp
    0x10588a06e <+4>:   pushq  %r15
    0x10588a070 <+6>:   pushq  %r14
    0x10588a072 <+8>:   pushq  %rbx
    0x10588a073 <+9>:   pushq  %rax
    0x10588a074 <+10>:  movq   %rsi, %r15
    0x10588a077 <+13>:  movq   %rdi, %r14
    0x10588a07a <+16>:  testq  %r14, %r14
    0x10588a07d <+19>:  je     0x10588a0f1               ; <+135>
    0x10588a07f <+21>:  movl   0x8(%r14), %eax
    0x10588a083 <+25>:  cmpl   $0x12, %eax
    0x10588a086 <+28>:  je     0x10588a0f1               ; <+135>
    0x10588a088 <+30>:  cmpq   %r15, 0x40(%r14)
    0x10588a08c <+34>:  je     0x10588a0f1               ; <+135>
    0x10588a08e <+36>:  cmpl   $0x1, %eax
    0x10588a091 <+39>:  jne    0x10588a0c4               ; <+90>
    0x10588a093 <+41>:  movq   0x58(%r14), %rbx
    0x10588a097 <+45>:  jmp    0x10588a0bf               ; <+85>
->  0x10588a099 <+47>:  cmpl   $0x2, 0x50(%rbx)
    0x10588a09d <+51>:  jne    0x10588a0ab               ; <+65>
    0x10588a09f <+53>:  movq   0x40(%r14), %rdi
    0x10588a0a3 <+57>:  movq   %rbx, %rsi
    0x10588a0a6 <+60>:  callq  0x105896b48               ; xmlRemoveID
    0x10588a0ab <+65>:  movq   %r15, 0x40(%rbx)
    0x10588a0af <+69>:  movq   0x18(%rbx), %rdi
    0x10588a0b3 <+73>:  movq   %r15, %rsi
    0x10588a0b6 <+76>:  callq  0x10588a0fc               ; xmlSetListDoc
    0x10588a0bb <+81>:  movq   0x30(%rbx), %rbx
    0x10588a0bf <+85>:  testq  %rbx, %rbx
    0x10588a0c2 <+88>:  jne    0x10588a099               ; <+47>
    0x10588a0c4 <+90>:  movq   0x18(%r14), %rbx
    0x10588a0c8 <+94>:  testq  %rbx, %rbx
    0x10588a0cb <+97>:  je     0x10588a0ed               ; <+131>
    0x10588a0cd <+99>:  cmpl   $0x12, 0x8(%rbx)
    0x10588a0d1 <+103>: je     0x10588a0ed               ; <+131>
    0x10588a0d3 <+105>: cmpq   %r15, 0x40(%rbx)
    0x10588a0d7 <+109>: je     0x10588a0e4               ; <+122>
    0x10588a0d9 <+111>: movq   %rbx, %rdi
    0x10588a0dc <+114>: movq   %r15, %rsi
    0x10588a0df <+117>: callq  0x10588a06a               ; <+0>
    0x10588a0e4 <+122>: movq   0x30(%rbx), %rbx
    0x10588a0e8 <+126>: testq  %rbx, %rbx
    0x10588a0eb <+129>: jne    0x10588a0d3               ; <+105>
    0x10588a0ed <+131>: movq   %r15, 0x40(%r14)
    0x10588a0f1 <+135>: addq   $0x8, %rsp
    0x10588a0f5 <+139>: popq   %rbx
    0x10588a0f6 <+140>: popq   %r14
    0x10588a0f8 <+142>: popq   %r15
    0x10588a0fa <+144>: popq   %rbp
    0x10588a0fb <+145>: retq   
```

I will try to setup another test project that actually fetches real data from the API I'm using in an attempt to see if the collection of different data is leading to this problem.

**Comment by a-ignatov-parc** [comment] 2018-10-19 08:03
Well, at least we fixed `SIGABRT`.

> The style warnings are still there in the real project and simulator.

As I mentioned earlier they are shown even without TVML app at all. I've posted a bug report to Apple, but there still no response.

> This "error" is logged each time a new page is pushed onto the navigationDocument.

I'll check it. Thanks!

And, I'll be very appreciated for new app build with steps to reproduce `EXC_BAD_ACCESS`.

**Comment by febbraro** [comment] 2018-10-22 20:06
Ok, here goes.  If you pull the same repo, but use the `fetching-from-api` branch I have this crashing consistently.  Here is the crazy part, this is the commit that gets the crashes to happen:

https://github.com/febbraro/xcode10-tvos12/commit/8eced2a6d3fcd05349dbc09473c4f6ec77d1c135

Basically, I added a couple `{ '' }` and that did it.  I could not get the same crashes when adding those to the master branch, the only real difference I could tell was that this fetching branch loads a document with a loadingTemplate during each HTTP request and then replaces that with the actual video document.

So select the video tile and then go back to the main journal screen. Doing that 10 or so time should cause the crashes.  Sorry for the delay I was having a hard time reproducing it in my TestApp, but think I got it.

**Comment by a-ignatov-parc** [comment] 2018-10-23 03:45
You are awesome! Thank you! I'll check it soon 👍

**Comment by a-ignatov-parc** [comment] 2018-10-23 09:21
@febbraro I think I managed to fix this issue once and for all. Please check [`v6.2.2`](https://github.com/a-ignatov-parc/tvdml/releases/tag/v6.2.2) release.

**Comment by febbraro** [comment] 2018-10-23 17:03
@a-ignatov-parc Great! I'm testing it now and for that main page it looks like you have fixed the crashes. Thanks! 

I have found another page in my app that can produce some crashes, its a search page, working up an example to demonstrate it now.

**Comment by a-ignatov-parc** [comment] 2018-10-23 17:10
> I have found another page in my app that can produce some crashes

Whoa! You've got some mighty skills for bug hunting 😂

Thanks a lot!

**Comment by febbraro** [comment] 2018-10-23 17:16
I know, I know. :) Thanks for working with me to track down the causes. I REALLY appreciate it.

**Comment by febbraro** [comment] 2018-10-23 18:36
Ok @a-ignatov-parc, I have merged and added to the `master` branch, so use that.  If you go to search and you can search for `workout`, then remove the last `t` and add it back. Perform the search around 5-10 times and you will get crashes.

`ITMLKit (8): EXC_BAD_ACCESS (code=1, address=0x51)`
```
libxml2.2.dylib`xmlSetTreeDoc:
    0x10e46906a <+0>:   pushq  %rbp
    0x10e46906b <+1>:   movq   %rsp, %rbp
    0x10e46906e <+4>:   pushq  %r15
    0x10e469070 <+6>:   pushq  %r14
    0x10e469072 <+8>:   pushq  %rbx
    0x10e469073 <+9>:   pushq  %rax
    0x10e469074 <+10>:  movq   %rsi, %r15
    0x10e469077 <+13>:  movq   %rdi, %r14
    0x10e46907a <+16>:  testq  %r14, %r14
    0x10e46907d <+19>:  je     0x10e4690f1               ; <+135>
    0x10e46907f <+21>:  movl   0x8(%r14), %eax
    0x10e469083 <+25>:  cmpl   $0x12, %eax
    0x10e469086 <+28>:  je     0x10e4690f1               ; <+135>
    0x10e469088 <+30>:  cmpq   %r15, 0x40(%r14)
    0x10e46908c <+34>:  je     0x10e4690f1               ; <+135>
    0x10e46908e <+36>:  cmpl   $0x1, %eax
    0x10e469091 <+39>:  jne    0x10e4690c4               ; <+90>
    0x10e469093 <+41>:  movq   0x58(%r14), %rbx
    0x10e469097 <+45>:  jmp    0x10e4690bf               ; <+85>
->  0x10e469099 <+47>:  cmpl   $0x2, 0x50(%rbx)
    0x10e46909d <+51>:  jne    0x10e4690ab               ; <+65>
    0x10e46909f <+53>:  movq   0x40(%r14), %rdi
    0x10e4690a3 <+57>:  movq   %rbx, %rsi
    0x10e4690a6 <+60>:  callq  0x10e475b48               ; xmlRemoveID
    0x10e4690ab <+65>:  movq   %r15, 0x40(%rbx)
    0x10e4690af <+69>:  movq   0x18(%rbx), %rdi
    0x10e4690b3 <+73>:  movq   %r15, %rsi
    0x10e4690b6 <+76>:  callq  0x10e4690fc               ; xmlSetListDoc
    0x10e4690bb <+81>:  movq   0x30(%rbx), %rbx
    0x10e4690bf <+85>:  testq  %rbx, %rbx
    0x10e4690c2 <+88>:  jne    0x10e469099               ; <+47>
    0x10e4690c4 <+90>:  movq   0x18(%r14), %rbx
    0x10e4690c8 <+94>:  testq  %rbx, %rbx
    0x10e4690cb <+97>:  je     0x10e4690ed               ; <+131>
    0x10e4690cd <+99>:  cmpl   $0x12, 0x8(%rbx)
    0x10e4690d1 <+103>: je     0x10e4690ed               ; <+131>
    0x10e4690d3 <+105>: cmpq   %r15, 0x40(%rbx)
    0x10e4690d7 <+109>: je     0x10e4690e4               ; <+122>
    0x10e4690d9 <+111>: movq   %rbx, %rdi
    0x10e4690dc <+114>: movq   %r15, %rsi
    0x10e4690df <+117>: callq  0x10e46906a               ; <+0>
    0x10e4690e4 <+122>: movq   0x30(%rbx), %rbx
    0x10e4690e8 <+126>: testq  %rbx, %rbx
    0x10e4690eb <+129>: jne    0x10e4690d3               ; <+105>
    0x10e4690ed <+131>: movq   %r15, 0x40(%r14)
    0x10e4690f1 <+135>: addq   $0x8, %rsp
    0x10e4690f5 <+139>: popq   %rbx
    0x10e4690f6 <+140>: popq   %r14
    0x10e4690f8 <+142>: popq   %r15
    0x10e4690fa <+144>: popq   %rbp
    0x10e4690fb <+145>: retq   
```

**Comment by febbraro** [comment] 2018-10-24 00:05
After beating up my app for about 30 minutes I have not been able to reproduce any of the crashes. Woohoo!!!! 🎉  

I will hit it pretty hard over the next day or so to see what comes of it, but so far it is looking good.  

Thanks for looking into it so quickly! 👍

**Comment by spunkedy** [comment] 2018-10-24 01:03
Yay

**Comment by a-ignatov-parc** [comment] 2018-10-24 04:03
> I have not been able to reproduce any of the crashes

We did it! 🙂

> I will hit it pretty hard over the next day or so to see what comes of it

Great! Let us know about the results! And feel free to open new issues if you'll find something 👍

**Closed by a-ignatov-parc** 2018-10-24 04:03 UTC

**Comment by febbraro** [comment] 2018-10-24 12:29
Just tested a bit more on a real device (running tvOS 12.0.1) and things are still looking good. Going to get a build together today and distribute to some users via TestFlight today and will report back if things pop up.  

Also, any word back on the bug report for styles?  I have reported a few bugs in the past and have never heard anything back, not sure what your experience is with these things.

**Comment by a-ignatov-parc** [comment] 2018-10-24 13:00
> any word back on the bug report for styles?

Nope. Two weeks and still no response.

Well, at least 3 bug reports (from minor to critical) had a response 🙂
